---
title: "ReactomeGSa usage "
output: html_notebook
---

```{r}
library(ReactomeGSA)
```


```{r}
# Load in example data
filename <- file.choose()
Prox1_norm <- readRDS(filename)
```

```{r}
available_methods <- get_reactome_methods(print_methods = FALSE, return_result = TRUE)
# only show the names of the available methods
available_methods$name
#> [1] "PADOG"  "Camera" "ssGSEA"
```

#Create an analysis request 
```{r}
# Create a new request object using 'Camera' for the gene set analysis
my_request <-ReactomeAnalysisRequest(method = "Camera")

my_request

```

```{r}
library(ReactomeGSA.data)
data(jerby_b_cells)
```


```{r}
#find a dataset 
gsva_result <- analyse_sc_clusters(jerby_b_cells, verbose = TRUE)
```

```{r}
pathway_expression <- pathways(gsva_result)
colnames(pathway_expression) <- gsub("\\.Seurat", "", colnames(pathway_expression))
# find the maximum differently expressed pathway
max_difference <- do.call(rbind, apply(pathway_expression, 1, function(row) {
    values <- as.numeric(row[2:length(row)])
    return(data.frame(name = row[1], min = min(values), max = max(values)))
}))

max_difference$diff <- max_difference$max - max_difference$min

# sort based on the difference
max_difference <- max_difference[order(max_difference$diff, decreasing = T), ]

head(max_difference)
```

```{r}
plot_gsva_pathway(gsva_result, pathway_id = rownames(max_difference)[1])
```

```{r}
# Additional parameters are directly passed to gplots heatmap.2 function
plot_gsva_heatmap(gsva_result, max_pathways = 15, margins = c(6,20))
```

```{r}
gsva_result_Prox1 <- analyse_sc_clusters(Prox1_norm, verbose = TRUE)
```

```{r}
pathway_expression_Prox1 <- pathways(gsva_result_Prox1)
# simplify the column names by removing the default dataset identifier
colnames(pathway_expression_Prox1) <- gsub("\\.Seurat", "", colnames(pathway_expression_Prox1))
pathway_expression_Prox1
```

```{r}
# find the maximum differently expressed pathway
max_difference <- do.call(rbind, apply(pathway_expression_Prox1, 1, function(row) {
    values <- as.numeric(row[2:length(row)])
    return(data.frame(name = row[1], min = min(values), max = max(values)))
}))

max_difference$diff <- max_difference$max - max_difference$min

# sort based on the difference
max_difference <- max_difference[order(max_difference$diff, decreasing = T), ]

head(max_difference)
```

```{r}
plot_gsva_pathway(gsva_result_Prox1, pathway_id = rownames(max_difference)[1])
```

```{r}
# Additional parameters are directly passed to gplots heatmap.2 function
plot_gsva_heatmap(gsva_result_Prox1, max_pathways = 15, margins = c(6,20))
```

```{r}
plot_gsva_pca(gsva_result_Prox1)
```

